### ISSUE TITLE
Do we need babel-polyfill in production

### ISSUE THREAD

**Issue by VladShcherbin** [gaearon/react-transform-boilerplate#101]
Since a lot of us use `redux` and `Object.assign`, don't we need to use `babel-polyfill` in production for the browser support (especially mobile support)?

Maybe it can be added to the configuration or in the readme faq?

**Comment by gaearon** [comment]
This project has no relation to Redux, and is only meant to show how to set up React Transform. In fact React Transform may not be the best option for Redux projects at all: https://github.com/reactjs/redux/pull/1455.

So I don’t think this is really relevant. It’s not a boilerplate in the sense of “gonna copy it for my next project”. It’s a boilerplate in the sense of “see the minimal configuration to get these tools working, and use it however you like”.
