### ISSUE TITLE
Debug in devtools

### ISSUE THREAD

**Issue by giltig** [gaearon/react-transform-boilerplate#103]
Hi,
I'm trying to debug with dev-tools but break point is not operated after hot module replacement occurs.
![image](https://cloud.githubusercontent.com/assets/5754742/12394797/ca8746fc-be06-11e5-8ac5-a7e9cbd7bce9.png)

**Comment by giltig** [comment]
Hmm I would recommend adding:
 devtool: 'cheap-module-eval-source-map' 
to the webpack.dev.config which solves the problem...

**Comment by gaearon** [comment]
You won’t hit the root `index.js` file again after hot reloading because it is handled by the components. Babel plugin with `react-transform-hmr` puts `module.hot` API calls into files where they see components, so those stop the hot update propagation.
