### ISSUE TITLE
How to view app in mobile device?

### ISSUE THREAD

**Issue by lukephills** [gaearon/react-transform-boilerplate#113]
If I navigate to `<my-ip>:3000` the device can't connect to the server.

Is it possible to view the app this way on a mobile or tablet for testing?

Thanks

**Comment by Tinple** [comment]
See [this](https://github.com/gaearon/react-hot-loader/issues/107)

**Comment by gaearon** [comment]
Not something I plan to do in this repo but feel free to contribute back if you get this working!
