### ISSUE TITLE
There are some problem and suggest.

### ISSUE THREAD

**Issue by minooo** [gaearon/react-transform-boilerplate#117]
* In some cases, the page does not automatically update, need to manually refresh the next.
* Can you provide a reasonable directory structure used in the production
* Is it possible to make some necessary for some modules to add description and explanation

**Comment by gaearon** [comment]
This is not meant as a boilerplate to copy and use in projects. It’s meant to show how a particular technique can be configured. We don’t plan to provide any opinionated structure for the projects.

As for point one, I hope https://github.com/gaearon/react-transform-boilerplate/issues/120#issuecomment-192716194 can bring some clarity on why some things can’t be updated automatically.
