### ISSUE TITLE
Weird behaviour when adding text

### ISSUE THREAD

**Issue by donaldpipowitch** [gaearon/react-transform-boilerplate#119]
When I change [this line](https://github.com/gaearon/react-transform-boilerplate/blob/master/src/App.js#L33) from `<div>` to `<div>foo` I'd expect that something like this would happen:

```
Counter (1): 1
Counter (5): 5

// insert `foo`
foo
Counter (1): 1
Counter (5): 5
```

But this seem to happen:

```
Counter (1): 1
Counter (5): 5

// insert `foo`
foo
Counter (1): 5  // state from counter (5)?
Counter (5): 0  // new state?
```

**Comment by gaearon** [comment]
Yeah, if you “move” stateful component, it’s going to lose its state because its key in the parent component changed. By adding a text between them, you’re effectively moving the second one to another index. This is consistent with how React normally works. You can enforce keeping the state by adding an explicit `key` to it.

**Comment by donaldpipowitch** [comment]
Thank you for your answer. Is this something which could be "solved" in the future. Is this a limitation which "works as intended"? This seems to limit the usefulness of hot reloading a lot.

**Comment by gaearon** [comment]
I don’t see how this can be solved. We can’t guess how you move text around in the editor. I don’t think it limits usefulness “a lot”. As soon as you add that node in between, further changes to it will preserve state of all children. The state is only lost *when* you insert nodes in the middle, and is only lost for items *after* the inserted node. And again, you can work around it by setting `key` explicitly when you’re doing shuffle-heavy work.
