### ISSUE TITLE
Example hot loading css (css-loader?module)

### ISSUE THREAD

**Issue by pruett** [gaearon/react-transform-boilerplate#12]
Are there any examples using this template combined with CSS modules as per https://github.com/css-modules/webpack-demo?

**Comment by hanfeisun** [comment]
+1

will css loader be added in the future?

**Comment by gaearon** [comment]
Yeah I think we can do it.

**Comment by pruett** [comment]
this should help https://github.com/pruett/react-transform-boilerplate/commit/b97eaf89d3abd8524924b8139dfe4470137e90db

do you want me to open a PR @gaearon ?

**Comment by ccoffey** [comment]
+1

**Comment by puradox** [comment]
+1

**Comment by LucaColonnello** [comment]
+1

**Comment by gaearon** [comment]
I think now that people use different tools for CSS, and I don’t want to give the impression that this project is the “opinionated boilerplate to get started” kind of project. It wasn’t meant to be something like this. It shows a single particular technique, and you are welcome to combine it with other techniques in other projects and boilerplates.
