### ISSUE TITLE
Doesn't work with react Component class wrapper

### ISSUE THREAD

**Issue by Igor10k** [gaearon/react-transform-boilerplate#123]
For example add in `App.js`

```js
class BaseComponent extends Component {

}
```

and change 

```js
export class App extends Component {
```

to

```js
export class App extends BaseComponent {
```

Next try to change the `render` method of the `App` class. HMR will print to console that the module was updated but nothing will actually change on screen.

**Comment by gaearon** [comment]
This is expected.

You can specify Babel plugin options manually and then add a custom list of `superclasses`. By default only `Component` and `React.Component` are recognised. You can check the present we are using to see how to configure the Babel plugin. 

In general inheritance is considered a bad practice in React components and should be avoided. It can almost always be replaced by composition in a better way.

**Comment by gaearon** [comment]
Correction: the relevant Babel plugin option is called `superClasses`. Still, I would rather suggest not using inheritance.

**Comment by Igor10k** [comment]
@gaearon This kind of inheritance is used in the react_on_rails project example https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/libs/components/BaseComponent.jsx . Seemed like a nice way to make all components implement the PureRenderMixin logic without specifying it manually for every component.
