### ISSUE TITLE
Error when using Webpack 2 and es2015-webpack preset

### ISSUE THREAD

**Issue by VladShcherbin** [gaearon/react-transform-boilerplate#124]
When using webpack 2 and the [suggested](https://gist.github.com/sokra/27b24881210b56bbaff7#babel-and-webpack) es2015-webpack preset, updating a component gives an error:

<img width="704" alt="screen shot 2016-03-16 at 5 14 35 am" src="https://cloud.githubusercontent.com/assets/6711845/13800082/876efd08-eb36-11e5-864e-4c41b827fa51.png">

If we use webpack 2 and es2015 preset - there is no error.

So, do we need to use es2015-webpack preset in prod and es2015 in dev?

**Comment by hanfeisun** [comment]
+1, it will be great if webpack2 is supported

**Comment by hanfeisun** [comment]
It seems that `2.10.0` webpack-hot-middleware already supports this:

https://github.com/glenjamin/webpack-hot-middleware/issues/70

**Comment by gaearon** [comment]
Can I ask you to try https://github.com/gaearon/react-hot-boilerplate/pull/61 with Webpack 2 instead? This project is going to be deprecated in favor of React Hot Loader 3 as described there.

**Comment by vladshcherbin** [comment]
@gaearon sure, I was trying to find a good boilerplate for easy package creation. Will try your new work. I like your packages and what you do! Thank you a lot. ❤️
