### ISSUE TITLE
Doesn't work with React-Router :(

### ISSUE THREAD

**Issue by mdebbar** [gaearon/react-transform-boilerplate#128]
I started using hot reloading and it gave me a huge productivity boost. Thanks everyone for making this possible!

The only problem I'm having now is that route components can't be hot-updated. I'm getting the following warning in my console:
> The following modules couldn't be hot updated: (Full reload needed) ...

```javascript
class MyRouteComponent extends React.Component {
  // ... any changes here can't be hot-updated :(
}

ReactDOM.render(
  <Router>
    <Route path="/" component={MyRouteComponent} />
  </Router>,
  document.body
);
```

Is there any workaround to make it work?

**Comment by gaearon** [comment]
Are you writing everything in a single file? Hot reloading will only work if you split the root component into a separate module.

**Comment by mdebbar** [comment]
Not in a single file. Here is what my main entry file looks like:
```javascript
import MyRouteComponent from "./my-route-component";

ReactDOM.render(
  <Router>
    <Route path="/" component={MyRouteComponent} />
    ...
  </Router>
  document.body
);
```

Maybe the entry file should be simpler than this? Like:
```javascript
import MyRouter from "./my-router";

ReactDOM.render(
  <MyRouter />,
  document.body
);
```
Would that work?

**Comment by gaearon** [comment]
Please provide a project reproducing the problem.

**Comment by gaearon** [comment]
Along with exact instructions to reproduce it

**Comment by gaearon** [comment]
Closing as there’s not enough information, and anyway a big change is coming: https://github.com/gaearon/react-hot-boilerplate/pull/61
