### ISSUE TITLE
Problems hot-reloading non-components.

### ISSUE THREAD

**Issue by cpsubrian** [gaearon/react-transform-boilerplate#13]
I've been trying out this hot-loading methodology in a redux app and have been running into issues with non-components not being hot-reloadable. Things like reducers and actions that export 'pure' functions that should be hot-swappable. I've been trying to dig into the hot reload internals to figure-out why but have hit a brick wall in my understanding of the system.

I forked this repo and converted it to a very simple redux app here: 
https://github.com/cpsubrian/react-transform-boilerplate

To reproduce, simply edit and save the reducer (such as changing `counter: state.counter + 1` to `counter: state.counter + 2`). It should result in the HMR warning below:

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
[HMR]  - ./src/reducer.js
```

At first I thought that maybe I needed to opt-in these modules specifically to the hot api, but editing `colors.js` works as expected without any specific hot api buy-in.

**Comment by cpsubrian** [comment]
To be more specific, using the standard setup with `react-hot-loader` works for me, but I much prefer this transform/middleware setup to using the full webpack-dev-server.

**Comment by danmartinez101** [comment]
You need to manually add reducer hot loading as of v2.0.0
You can find an example of what this looks like here: 
https://github.com/rackt/react-redux/releases/tag/v2.0.0

**Comment by cpsubrian** [comment]
Thanks @danmartinez101 ! cpsubrian/react-transform-boilerplate@f95ddad worked like a charm.

For future reference, the reason why the reducer was not inherently hot-loadable is due to the export being consumed by createStore and being wrapped in some way? In other words, how does webpack know what is/is-not 'self accepted'?

**Comment by gaearon** [comment]
Webpack doesn't. [react-transform-webpack-hmr](https://github.com/gaearon/react-transform-webpack-hmr) [tells it to accept a hot update](https://github.com/gaearon/react-transform-webpack-hmr/blob/8b2e1174f11fc4b7be8b6a4a8513a49f38eb29db/src/development.js#L28-L35) if it finds a React component.

**Comment by cpsubrian** [comment]
Right, but something is causing `colors.js` to be hot loaded, thats what confuses me.

**Comment by gaearon** [comment]
This is Webpack's hot module replacement bubbling mechanism. If nothing “accepts” the module, the update bubbles, and now all of its “parents” (whoever imported this module) need to be accepted. In this case, it is imported from a React component, so `react-transform-webpack-hmr` picks it up.

**Comment by cpsubrian** [comment]
Ok , that does make a lot more sense now that I remember what I was watching in the debugger. Was confused why it would bubble up all the way to parent module id === 0, which would cause it to break out of accepting the hot reload. Good to know that somewhere up the chain someone has to accept the load.
