### ISSUE TITLE
Proxy index.html

### ISSUE THREAD

**Issue by brenoc** [gaearon/react-transform-boilerplate#16]
In this boilerplate, it assumes that the `index.html` is at the same source code as the React code. This was not my case. I need a proxy to my `index.html` because it is served by a remote server.

I used to use webpack-dev-server, and I had it set at `webpack.config.js` like so:

```js
  devServer: {
    publicPath: publicPath,
    port: 3000,
    hot: true,
    inline: true,
    proxy: {
      '*': 'http://api.example.com'
    }
  }
```

I managed to proxy the requests like webpack-dev-server did and it solved my issues. If anyone is having the same issue, you can check how I changed `server.js` to work in this scenario here:
https://gist.github.com/brenoc/e0ba0979014a62a1ff1c

Sorry to create an issue for this, but I found it helpful to share it. Maybe add it to the README?

**Comment by vincentfretin** [comment]
@brenoc I have the same scenario, index.html generated and served by another application. I use the following configuration.
The important parts are ```'webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr'```
and output.publicPath and of course use http://localhost:3000/static/bundle.js in your served index.html when in development mode.

```javascript
var path = require('path');
var webpack = require('webpack');

module.exports = {
  devtool: '#cheap-module-eval-source-map', // http://webpack.github.io/docs/configuration.html#devtool
  entry: [
    'webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr',
    './src/index'
  ],
  output: {
    path: path.join(__dirname, 'javascripts'),
    filename: 'bundle.js',
    publicPath: 'http://localhost:3000/static/'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['babel?optional=runtime'],
      include: path.join(__dirname, 'src')
    }]
  }
};
```

**Comment by gaearon** [comment]
I'm closing as non-actionable.
If you'd like this to be in README please make a pull request.
