### ISSUE TITLE
NoErrorsPlugin breaks compatibility with eslint-loader

### ISSUE THREAD

**Issue by jonathanewerner** [gaearon/react-transform-boilerplate#19]
We are using [eslint-loader](https://github.com/MoOx/eslint-loader) to enforce linting rules independent of individual editor setups. eslint-loader doesn't work with NoErrorsPlugin. Is this a hard dependency of react-transform?

**Comment by gaearon** [comment]
I don't think it's a hard dependency. Try without it and let us know. ;-)

**Comment by jonathanewerner** [comment]
Ok. I tried without and could not detect any changes in functionality.

**Comment by gaearon** [comment]
I killed it.
