### ISSUE TITLE
Always servers index.html

### ISSUE THREAD

**Issue by vincent-dm** [gaearon/react-transform-boilerplate#22]
The devServer.js always serves the index.html page, even when I request a file which exists in the directory defined in publicPath.

Any idea why?

**Comment by lucasmotta** [comment]
Mainly because of this piece of code on the `devServer.js` file:

```js
app.get('*', function(req, res) {
  res.sendFile(path.join(__dirname, 'index.html'));
});
```
That means that all your files (`get('*')`) will render the index.html no matter what. To fix that you can serve the static files before:

```js
app.use(express.static('public'));
```

You can read more about [here](http://expressjs.com/starter/static-files.html), but if still doesn't work, let me know.

**Comment by gaearon** [comment]
This is just Express and Webpack.
This boilerplate is meant to demonstrate React Transform and Webpack Hot Middleware.
It is not meant to implement every feature a project might need.

https://github.com/gaearon/react-transform-boilerplate#i-cant-serve-images--use-different-html-file--etc

**Comment by ngerritsen** [comment]
@lucasmotta That solution doesn't actually work because the get(*) overrides the calls

**Comment by vincent-dm** [comment]
Yes, that is also what confused me, since I'm not familiar with Express and wanted to build a small demo on top of this example. Changing the code to `app.get('/', (req, res) => {...` in combination with the code from @lucasmotta did the trick.

**Comment by lucasmotta** [comment]
@ngerritsen if you serve the static files before, it should work and the * middleware won't be even executed. Express executes the middleware in the order your add them.

**Comment by gaearon** [comment]
I'm happy to accept a PR making this behave more intuitively.
