### ISSUE TITLE
Question: devServer example using Hapi.js

### ISSUE THREAD

**Issue by tylermadison** [gaearon/react-transform-boilerplate#25]
Does this work with Hapi?

**Comment by gaearon** [comment]
I don't know. [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware) is probably a better place to ask, as it is the Express-specific piece. You can also use [webpack-dev-server](http://webpack.github.io/docs/webpack-dev-server.html) if you prefer it.
