### ISSUE TITLE
Doctype required?

### ISSUE THREAD

**Issue by clessg** [gaearon/react-transform-boilerplate#28]
This is surely a stupid question, so I apologize in advance, but isn't the doctype required in `index.html` for HTML5 documents?

Adding the HTML5 doctype to the top of `index.html` causes the page to render slightly differently in Chrome and Firefox. (Not specific to React. The same happens for the pure HTML prototype.)

**Comment by gaearon** [comment]
I suppose so. This is really not the point of this boilerplate. If you can make it better please make PRs! :wink:

**Comment by clessg** [comment]
Yes sir, of course. This is why sleep is important. #30
