### ISSUE TITLE
Does'n work in vagrant

### ISSUE THREAD

**Issue by terry-s** [gaearon/react-transform-boilerplate#33]
There is some approaches to use it on vagrant vm?

I have tried to use pure boilerplate. I think it blocks by vagrant proxy which connect my vm to my host.

**Comment by gaearon** [comment]
Does https://github.com/gaearon/react-hot-boilerplate work? If it does, then you should ask about configuration in [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware). If it doesn't, you should ask in Webpack repo.

Unfortunately this boilerplate is only for showing Babel and webpack-hot-middleware setup: we can't solve upstream issues.

**Comment by gaearon** [comment]
If you do find a solution, please let us know though. :-)

**Comment by cbrwizard** [comment]
I am also interested in this
