### ISSUE TITLE
Heroku deploy

### ISSUE THREAD

**Issue by italoacasas** [gaearon/react-transform-boilerplate#35]
Hi guys sorry for the question if I want deploy this in Heroku, i need a prodServer true?

**Comment by danmartinez101** [comment]
Yes, you would want to make sure the build pack runs the webpack build in production mode and then you'd serve up the built directory using something like https://github.com/hapijs/hapi or express.

**Comment by italoacasas** [comment]
Yes thanks I fix this last week, I create **another** boilerplate ;)

[react-boilerplate](https://github.com/spaceSignal/react-boilerplate)

**Comment by danmartinez101** [comment]
Ah, cool! If your issue is resolved can you close this issue? Thanks!

**Comment by gaearon** [comment]
Not a real issue so I'm closing.
