### ISSUE TITLE
Components get mixed up when using classic syntax

### ISSUE THREAD

**Issue by rdxi** [gaearon/react-transform-boilerplate#36]
Hot reload uses different component after you change component places in code.
Bug only appears when using classic syntax. With ES6 syntax everything works as expected.
Manual page reload also fixes it.
![react-components-mixup](https://cloud.githubusercontent.com/assets/2130713/10235468/92194920-68be-11e5-912d-4eda7d052fde.gif)

Steps: 
1. Make 2 components inside App.js: App and Banana. Export only App component.
2. In index.js import App component and render it to page.
3. Inside App.js change Banana and App places.
4. Save

Expected behavior: App is rendered
Actual behavior: Banana is rendered 

Can anyone else reproduce it?

**Comment by gaearon** [comment]
If you use `createClass()` syntax please also use `babel-plugin-react-display-name`: https://github.com/gaearon/babel-plugin-react-transform/issues/24
Then it should work as intended.

**Comment by rdxi** [comment]
Yep with plugin it works as expected, thanks!
