### ISSUE TITLE
slackin invitation wot working

### ISSUE THREAD

**Issue by bcbcarl** [gaearon/react-transform-boilerplate#37]
I invited myself via http://www.reactiflux.com/ and still cannot receive an invitation letter.

![screen shot 2015-10-03 at 1 32 08 pm](https://cloud.githubusercontent.com/assets/135734/10261625/31ea4732-69d3-11e5-9bf5-d38f331f4003.png)

**Comment by gaearon** [comment]
Hi! We're not affiliated with Reactiflux and can't provide support for it in this repository.

**Comment by bcbcarl** [comment]
Thank you for your reply. Slack disabled new user creation.

https://github.com/reactiflux/www/issues/3
