### ISSUE TITLE
"[HMR] Reloading page"  page isn't reloading

### ISSUE THREAD

**Issue by tnrich** [gaearon/react-transform-boilerplate#38]
The rest of the functionality seems to be working, but when I make a change that requires a reload, my browser window isn't auto-reloading. I'm using google chrome. 

Anyone know how to fix this?

**Comment by tnrich** [comment]
Digging in a teeny bit further, it looks like this line

```
if (reload) window.location.reload()
```

is being called with reload=false. 

Anyone know how to configure that variable to be true by default?

**Comment by gaearon** [comment]
Is this something that should be configured with [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware)?

**Comment by spektroskop** [comment]
Change your entry config to "webpack-hot-middleware/client?reload=true"

**Comment by tnrich** [comment]
Awesome I'll try it out! Thanks!

**Comment by barock19** [comment]
It's only reload for the first change ..

**Comment by CraigMcKenna** [comment]
Seems that **any change** requires reloading.  I don't think hot loading is working.  Am I missing something?

**Comment by barock19** [comment]
Have you configure the .babelrc ?

**Comment by CraigMcKenna** [comment]
No I have not done anything with .babelrc  What would you suggest?  Maybe I just misunderstand hot loading...

Any time I save a change to a file the entire page is refreshed.  Is this the way it's supposed to work?

**Comment by tnrich** [comment]
@spektroskop can the `reload=true` option be made into the default option?

**Comment by tnrich** [comment]
It doesn't look like it has been..
