### ISSUE TITLE
reloading page after an error loads an outdated build

### ISSUE THREAD

**Issue by matthewmueller** [gaearon/react-transform-boilerplate#39]
I've noticed this on most webpack builds and I'm not sure if it's a configuration issue, a bug or intentional. 

But if you have an error, you get the red screen. This is helpful, but if you reload the page you get the old build, which is pretty confusing. Then if you make a change again, it'll error out.

Any ideas on how to fix this?

**Comment by gaearon** [comment]
Does removing `NoErrorPlugin` from Webpack config help?

**Comment by pawsong** [comment]
@gaearon I had the same problem and removing `NoErrorPlugin` fixed this issue. Thanks! May I ask you the reason why you put `NoErrorPlugin` in the boilerplate?

**Comment by gaearon** [comment]
Fair enough, I removed it.
