### ISSUE TITLE
Broken in Safari

### ISSUE THREAD

**Issue by yoshicarroll** [gaearon/react-transform-boilerplate#4]
1. Change
<Counter increment={1} color={NICEer} /> 

2. Save
Get this in the console:

[Log] [HMR] bundle rebuilding
[Log] [HMR] bundle rebuilt in 153ms
[Log] [HMR] Checking for updates on the server...
[Log] [React HMR] Patching Counter
[Log] [React HMR] Patching App
[Log] [HMR] Updated modules:
[Log] [HMR]  - ./src/App.js
[Log] [HMR] App is up to date.
[Error] Error
	tryRender
	_renderValidatedComponentWithoutOwnerOrContext
	_renderValidatedComponent
	ReactCompositeComponent__renderValidatedComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	performUpdateIfNecessary
	performUpdateIfNecessary
	runBatchedUpdates
	perform
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	(anonymous function) ([native code], line 0)
	closeAll
	perform
	batchedUpdates
	enqueueUpdate
	enqueueUpdate
	enqueueForceUpdate
	forceUpdate
	(anonymous function)
	forEach
	(anonymous function)
[Error] Error: Cannot parse given Error object
	perform (undefined, line 260)
	batchedUpdates
	enqueueUpdate
	enqueueUpdate
	enqueueForceUpdate
	forceUpdate
	(anonymous function)
	forEach ([native code], line 0)
	(anonymous function)

**Comment by gaearon** [comment]
What is the exact code you're running? What Safari version are you using? Have you turned off extensions? I can't repro this.

**Comment by yoshicarroll** [comment]
Safari Version 8.0.8 (10600.8.9) on OSX 10.10.5 (14F27)
Running current master.

npm install
npm start
Point Safari to http://localhost:3000
In App.js change 
        <Counter increment={1} color={NICE} />
to
        <Counter increment={1} color={NICEr} />

Notice the extra r on NICE.

**Comment by yoshicarroll** [comment]
Safari Version 8.0.8 (10600.8.9) on OSX 10.10.5 (14F27)
Running current master.

npm install
npm start
Point Safari to http://localhost:3000
In App.js change 
 increment={1} color={NICE}
to
 increment={1} color={NICEr}

Notice the extra r on NICE.

**Comment by gaearon** [comment]
Oh, indeed! Please file this with [redbox-react](https://github.com/KeywordBrain/redbox-react), as it's their issue.

**Comment by gaearon** [comment]
I filed as https://github.com/KeywordBrain/redbox-react/issues/8.

**Comment by davidpfahler** [comment]
@yoshicarroll @gaearon Fixed in latest [redbox v1.1.1](https://github.com/KeywordBrain/redbox-react/releases/tag/v1.1.1). Thanks for reporting!
