### ISSUE TITLE
Normal compilation in development mode?

### ISSUE THREAD

**Issue by Anahkiasen** [gaearon/react-transform-boilerplate#40]
Since HMR plugin needs to be enabled in the `.babelrc` how would you go about making the `webpack` command work in local? Currently doing `BABEL_ENV=production webpack` cause otherwise I get the `locals[0]` error where it tells me I bundled react-transform when I'm not in hot mode

**Comment by gaearon** [comment]
>Currently doing BABEL_ENV=production webpack cause otherwise I get the locals[0] error where it tells me I bundled react-transform when I'm not in hot mode

That sounds reasonable.
You can also put configuration in `babel-loader`'s `query` instead of `.babelrc`—this way you can put it inline with Webpack dev or production config.

**Comment by Anahkiasen** [comment]
Ah good idea, will do that

**Comment by arturi** [comment]
But what’s the best way to handle production? Right now I moved configuration in ```babel-loader``` as you suggested and I run the app like this ```NODE_ENV=development node index.js ```. Then in my code I have conditions:

```
let webpackConfig;
if (process.env.NODE_ENV === 'production') {
  webpackConfig = require('../webpack.config.prod');
} else {
  webpackConfig = require('../webpack.config.prod');
}
```
and
```
if (process.env.NODE_ENV === 'development') {
  app.use(require('webpack-dev-middleware')(compiler, {
    noInfo: true,
    publicPath: webpackConfig.output.publicPath
  }));
}
``` 

Is this the way to do it or am I missing something? Is it ok not to precompile the bundle for production, but to let Webpack middleware serve it from memory? Thanks!

**Comment by matthewoates** [comment]
More simply, how do you inline all of this information in a query in the webpack json file?

```
{
  "stage": 0,
  "env": {
    "development": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }
      }
    }
  }
}

```

**Comment by Anahkiasen** [comment]
Put it in a separate file then require it

**Comment by matthewoates** [comment]
Thanks for the quick reply Anahkaisen.

I was wondering where the data should actually fit in the webpack file. I wasn't able to get anything to work.

```
// webpack.config.json
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel?nonStandard=true',
        exclude: /node_modules/,
        query: require('./babel.config')
      },
      ...
```

Am I missing something here? I'm under the impression that this needs to be specified where we add babel as a loader.

**Comment by coodoo** [comment]
@matthewoates In case you're still looking to solve this issue, have a look at [this](https://github.com/gaearon/react-transform-boilerplate/issues/58#issuecomment-152777343).
