### ISSUE TITLE
Does not work in IE < 11

### ISSUE THREAD

**Issue by SimenB** [gaearon/react-transform-boilerplate#41]
The class call check in babel throws in IE 9 & 10. Happens in our app as well, unsure which babel-plugin messes up.

React hot loader works for our app, so going back to that for now

**Comment by gaearon** [comment]
Please provide more details.
Is this particular boilerplate throwing in IE < 11?

See also https://github.com/gaearon/react-proxy/issues/27

**Comment by SimenB** [comment]
Aye, doing git clone, then `npm i` followed by `npm start` and opening `localhost:3000` fails in IE 8-10.

Your linked issue is probably the real issue, yeah...

React hot loader works though, would be a shame to have to keep using deprecated tools to support IE < 11

**Comment by gaearon** [comment]
It works because it overwrites the existing classes.
We could change `react-proxy` to do that too, but I'd rather avoid this if possible.

**Comment by SimenB** [comment]
The check throwing is this: `function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }`, if it helps.

**Comment by SimenB** [comment]
I _think_ I've avoided the proto-problem with a transform, as I mentioned in the issue you linked, and I get another exception

**Comment by SimenB** [comment]
@gaearon Any idea which repo I should report the bug in? Doesn't belong in here :smile:

**Comment by gaearon** [comment]
Hey, sorry I'm slow to respond on this.
IE11 is not a priority right now because I have tons of issues to fix with 0.14 and it requires changes across all repos, so that's what I'm busy with.
After that I'll try to look into IE issues but not sooner.

**Comment by gaearon** [comment]
Let's discuss in https://github.com/gaearon/react-proxy/issues/27.
