### ISSUE TITLE
Potential enhancement: some restructuring & including isomorphic React

### ISSUE THREAD

**Issue by inxilpro** [gaearon/react-transform-boilerplate#42]
I have a similar boilerplate at [inxilpro/react-redux-isomorphic-hot-boilerplate](https://github.com/inxilpro/react-redux-isomorphic-hot-boilerplate).  The notable changes are:

  1. All dependencies are the latest versions (including `react-0.14-rc1`)
  2. React is implemented in an isomorphic fashion
  3. Directory structure is a little more split up, into:
      - **client/** for client code
      - **server/** for dev and production server code
      - **webpack/** for webpack configs
      - _Root still contains `package.json` etc_
  4. Redux and redux-devtools are included
  5. `react-transform` is configured in the webpack config instead of the `.babelrc` file
  6. Feature flags `__DEV__` `__ON_SERVER__` and `__ON_CLIENT__` are added
  7. _As well as a few other minor tweaks_

If there's anything in that list that you'd be interested in receiving PR's for, please let me know! I'd much rather contribute to this repo than maintain my own. I just wanted to get something up so you could take a look.

If not, that's fine too :)

Chris

**Comment by inxilpro** [comment]
Looks like react 0.14 is out! Updating :)

**Comment by azaharakis** [comment]
One of the issues I had with hot loading for Universal apps using the old hot loader was the mismatch generated from the react code that gets swapped out client side to what originally created on the server when it was first fired up. would be great to discuss possible solutions for this problem :)

**Comment by meric** [comment]
With Isomorphic apps, anyone know how to even define a React.Component in server.js? I'm getting ```
throw new Error('locals[0] does not appear to be a `module` object with Hot Module ' + 'replacement API enabled. You should disable react-transform-hmr in ' + 'production by using `env` section in Babel configuration. See the ' + 'example in README: https://github.com/gaearon/react-transform-hmr');
```

**Comment by yourcelf** [comment]
@meric not sure if you're still stuck on that, but I was able to solve that same issue (`locals[0] does not appear to be a module...`) in an isomorphic app by moving the transform declaration out of babelrc and into to the webpack config.  That way, the server is not patching in the hot module loader when it loads the components, but the client always is.

Here's my working webpack.config.dev.js:

    "use strict";

    var path = require('path');
    var webpack = require('webpack');

    module.exports = {
      devtool: 'cheap-module-eval-source-map',
      resolve: {
        root: path.join(__dirname, 'src')
      },
      entry: [
        'eventsource-polyfill', // necessary for hot reloading with IE
        'webpack-hot-middleware/client',
        path.join(__dirname, 'src', 'client', 'index')
      ],
      output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/static/'
      },
      plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
      ],
      module: {
        loaders: [{
          test: /\.jsx?/,
          loader: 'babel',
          include: [path.join(__dirname, 'src')],
          query: {
            "presets": ["react-hmre"]
          }
        }]
      }
    }

.babelrc:

    {
      "presets": [
        "react",
        "es2015",
        "stage-2"
      ]
    }

relevant versions:

    "babel-core": "^6.4.5",
    "babel-loader": "^6.2.1",
    "babel-plugin-react-transform": "^2.0.0",
    "babel-plugin-transform-runtime": "^6.4.3",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-react-hmre": "^1.0.1",
    "babel-preset-stage-2": "^6.3.13",
    "eventsource-polyfill": "^0.9.6",
    "webpack-dev-middleware": "^1.5.1",
    "webpack-hot-middleware": "^2.6.4"

@azaharakis: I also ran into problems with server/client react code mismatches at first, but got around it, weirdly, by just wrapping the server-rendered markup in an extra div, as suggested here: http://stackoverflow.com/a/33521172/85461.  

e.g. on server:

    <div id='root'><div>${serverMarkup}</div></div>

on client:

    render(markup, document.getElementById('root'));

**Comment by meric** [comment]
@yourcelf Thanks! If I remember correctly, I was able to resolve it by separating out the babelrc run for the client and the one run on the server js.

**Comment by gaearon** [comment]
I don’t intend to make this boilerplate more powerful. It exists for a single purpose: to show how RT is configured. I’m happy to see people creating more boilerplate projects that have a bigger scope but this isn’t something I’m personally interested in. Thanks!
