### ISSUE TITLE
[Announcement] Please don't create React 0.14-related PRs

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-transform-boilerplate#44]
Hi all,

Thanks a lot for sending 0.14-related PRs.
I know it's out, and I'm working on releasing updates for React Transform-related packages.

Currently, sending PRs doesn't help because it's not hard for me to fix the warnings—the issue is in coordinated release of all packages (React Redux, DevTools, React Transform, etc) and fixing compatibility issues in the tooling. I will do my best to transition everything to 0.14 this week.

**In the meantime, please don't send PRs related to React 0.14 to React Transform, Redux, and related projects.**

Thanks.

**Comment by mik01aj** [comment]
> I will do my best to transition everything to 0.14 this week.

Any progress?

**Comment by aldendaniels** [comment]
@mik01aj - It looks like @ZillDing's PR to support React 0.14 got merged yesterday.

**Comment by gaearon** [comment]
It wasn't really “support” for 0.14.
The PR that got merged just bumps the packages.
I merged it because it seems that people prefer incomplete support to seeing old package versions. :wink:

However React Transform still doesn't support hot reloading functional components that are new in 0.14.
I will have time to work on this in the following weeks, but not right now.

**Comment by Spacerat** [comment]
That doesn't make any sense. Why update the React version when it's not supported? It kind of defeats the point of a boilerplate.

**Comment by gaearon** [comment]
I'll close for now. You can track https://github.com/gaearon/babel-plugin-react-transform/issues/57 if you're interested in support for functional components.
