### ISSUE TITLE
Unable to get react-transform-boilerplate working with Django

### ISSUE THREAD

**Issue by vitalybe** [gaearon/react-transform-boilerplate#46]
I had react-hot-loader working with django working by following [this](http://owaislone.org/blog/webpack-plus-reactjs-and-django/) article. I've tried to change it to the new react-transform. 

Everything seems to be loading fine but browser reload doesn't occur and I am getting no HMR related messages in console. The only malfunctioning hint that I got is the following log from Django server:
```
"GET /__webpack_hmr/ HTTP/1.1" 404 1700       
"GET /__webpack_hmr HTTP/1.1" 301 0           
```
Django is running on port 80 and webpack dev server on port 3000. I assume that the problem I am experiencing is that __webpack_hmr should be called on the webpack-dev-server and not on django.

Could someone point me to where is the port/address of `GET /__webpack_hmr` is set and whether it can be changed?

**Comment by razh** [comment]
@vitalybe 

You can specify it in the `path` for `webpack-hot-middleware/client`:

```js
  entry: [
    'webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr',
    './src/index'
  ],
```

https://github.com/gaearon/react-transform-boilerplate/blob/82cb8b7c48498949b28a23057c339a892663d0ac/webpack.config.dev.js#L7

You may also need to set CORS headers on responses from `devServer.js`:

```js
app.use(function(req, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  next();
});
```

**Comment by NeXTs** [comment]
@razh :+1: big thanks
I stumbled upon same issue while trying to integrate with php project

**Comment by NeXTs** [comment]
No, this don't help :(
Specifying **?path=http://localhost:3000/__webpack_hmr** DOES provide access to __webpack_hmr at custom port 3000

But after triggering first source change - server returns SINGLE response with content of my static html file, not JSON with list of updates as I might expect. (it does return correct JSON response in case using same port for both server and webpack-hot-middleware)
```
Remote Address:127.0.0.1:80
Request URL:http://localhost/static/12813d883d25bbe64a3f.hot-update.json
Request Method:GET
Status Code:200 OK
```
Response
```
<!doctype html>
<html>
  <head>
    <title>React Transform Boilerplate</title>
  </head>
  <body>
    <div id='root'>
    </div>
    <script src="http://localhost:3000/static/bundle.js"></script>
  </body>
</html>
```
Afterwards it ignores next update triggers and don't respond at all.
Does someone found workaround for this?

**Comment by NeXTs** [comment]
Aha, okay.
http://localhost:3000/static/12813d883d25bbe64a3f.hot-update.json

does return correct JSON.
How to force webpack-hot-middleware to make call with 3000 port?

**Comment by gaearon** [comment]
You don't *have to* use Webpack Hot Middleware. Just keep using Webpack Dev Server if that works for you. :-)

**Comment by NeXTs** [comment]
I've never used Webpack Dev Server before but for curiosity tried it just a moment ago and experienced same behaviour.
Anyway finally I made it work by setting
```
{
  output: {
    ..
    publicPath: 'http://localhost:3000/static/'
  }
}
```

**Comment by gaearon** [comment]
>I've never used Webpack Dev Server

What did you use with React Hot Loader?

**Comment by nlhkh** [comment]
Out of curiosity, why do you prefer `webpack-dev-middleware` over `webpack-dev-server`?

**Comment by weblancaster** [comment]
@nlhkh `webpack-dev-middleware` if you are using a dynamic server.. you'd want to add the middleware that way all connections to DB or API's and process work.. Using just `webpack-dev-server` would have to do a bunch of work around to achieve what you can achieve with `webpack-dev-middleware` out-of-the-box.

**Comment by JoshAddington** [comment]
The `entry` settings that @razh offered work for me in getting react-transform working with Django. :+1:

**Comment by gaearon** [comment]
Closing as non-actionable.
