### ISSUE TITLE
multiple entry points

### ISSUE THREAD

**Issue by mcharytoniuk** [gaearon/react-transform-boilerplate#47]
I am trying to setup hot module replacement to generate exact same pathname for scripts as the webpack cold build does. I have some problems with CommonsChunkPlugin  (https://github.com/webpack/docs/wiki/optimization#multi-page-app). Is it supported by hot module replacement?

**Comment by benglass** [comment]
I'm working on trying to get this setup functionality with multiple entry points and my progress thus far is that this config works

```
  entry: {
    vendor: ['jquery', 'react', 'webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr'],
    index: ['./src/index', 'webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr']
  },
```

Note that it seems to be necessary to include the webpack-hot-middleware in each entry point or I get the message "Nothing hot updated" when I make changes to my files. Not sure if I'm on the right track here or not.

**Comment by benglass** [comment]
I have pushed my complete config up. Its a WIP and needs considerable cleanup (ignore webpack.config.prod, all of the relevant configuration is in the dev file right now) but it definitely seems to represent a working configuration that uses react transform boilerplate with multiple entry points

https://github.com/benglass/webpack-hot-reload-config

@gaearon If it is correct that using this will multiple entry points requires adding the webpack-hot-middleware/client to teach entry point I can submit a PR to the troubleshooting part of this repo. This seems to be related to this item: https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#i-see-hmr-nothing-hot-updated-and-nothing-happens-when-i-edit-appjs

**Comment by vincentfretin** [comment]
If somebody can write a PR to add this to the README, it would be great.

**Comment by benglass** [comment]
@vincentfretin I have a feeling that my config might not be 100% right or optimal (specifically having to hardcode the reference to http://localhost:3000/__webpack_hmr into every endpoint). If anyone can confirm whether this is a "correct" approach vs. a work around or sub optimal I can submit a PR.

I also wasnt sure if there was any desired to provide an alternate webpack.multipleentrypoints.js file or something like that as an example?

**Comment by vincentfretin** [comment]
My colleague uses this in a project:

```javascript
var path = require('path')
var webpack = require('webpack')

module.exports = {
  devtool: '#cheap-module-eval-source-map', // http://webpack.github.io/docs/configuration.html#devtool
  entry: {
    editcategoriesmapping: ['webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr',
    './src/js/editcategoriesmapping/index'],
    offersearch: ['webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr',
    './src/js/offersearch/index'],
    previewoffer: ['webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr',
    './src/js/previewoffer/index'],
  },
  output: {
    path: path.join(__dirname, 'build'),
    filename: '[name].js',
    publicPath: 'http://localhost:3000/static/'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['babel?optional=runtime'],
      include: path.join(__dirname, 'src')
    }]
  }
}
```

**Comment by benglass** [comment]
Interesting, it looks like its required to add those webpack-hot-middleware/client?path=* with the __webpack_hmr to every module. It feels like this is missing from the documentation but I'm not sure where this should live. In this project's readme? In the webpack-hot-middleware docs? Both?

**Comment by vincentfretin** [comment]
maybe it's better in webpack-hot-middleware and a link to there from react-transform-boilerplate

**Comment by benglass** [comment]
@vincentfretin I think you are correct, there is actually pretty much the same conversation going on in an issue in the webpack-hot-middle repo at https://github.com/glenjamin/webpack-hot-middleware/issues/33 so I have asked about whether this is the correct approach and will submit a PR adding some docs/examples when I have confirmation.

**Comment by danmactough** [comment]
What I've found is that it's the order that matters:

Broken
```js
const config = {
  entry: {
    A: [ './src/a.js', 'webpack-hot-middleware/client?reload=true' ],
    B: [ './src/b.js', 'webpack-hot-middleware/client?reload=true' ]
  },
  .
  .
  .
};
```
Works
```js
const config = {
  entry: {
    A: [ 'webpack-hot-middleware/client?reload=true', './src/a.js' ],
    B: [ 'webpack-hot-middleware/client?reload=true', './src/b.js' ]
  },
  .
  .
  .
};
```

Am I crazy? Is this an anomaly?

**Comment by hanfeisun** [comment]
+1  

It will be great if contents about multiple entry points could be added to README. 

Or better if it could be added to the boilerplate directly..

**Comment by gaearon** [comment]
Added to README.
