### ISSUE TITLE
Usage without JSX?

### ISSUE THREAD

**Issue by legomind** [gaearon/react-transform-boilerplate#51]
Any examples would be helpful.

**Comment by CraigMcKenna** [comment]
Any JavaScript works.  It doesn't have to be JSX.

Example: replace the contents of *./src/index.js*

```javascript
console.log('bundling from index.js');
```

**Comment by legomind** [comment]
So I still must run my javascript through babel?

**Comment by CraigMcKenna** [comment]
Only if you want to transpile your code.

**Comment by legomind** [comment]
From what I understand, this boilerplate uses babel plugins for the hot-module reloading.

Coffescript compiles to ES5 javascript. Other than to use the babel plugins, I have no need to babel.
So in order to use react hotmodule reloading, my webpack should load my .coffee files to coffescript-loader -> babel -> bundle.js

**Comment by Cottin** [comment]
@legomind just a quick question, did you get this hot reloading to work with coffee using your idea about "load my .coffee files to coffescript-loader -> babel-loader -> bundle.js" ?
