### ISSUE TITLE
Why set NODE_ENV twice?

### ISSUE THREAD

**Issue by theneva** [gaearon/react-transform-boilerplate#54]
I'm looking through the code and don't understand why the environment variable NODE_ENV is set in both [webpack.config.prod.js](https://github.com/gaearon/react-transform-boilerplate/blob/master/webpack.config.prod.js#L16-L19):

```js
new webpack.DefinePlugin({
  'process.env': {
    'NODE_ENV': JSON.stringify('production')
  }
}),
```

... and [package.json's `build:webpack` task](https://github.com/gaearon/react-transform-boilerplate/blob/master/package.json#L7):

```json
"build:webpack": "NODE_ENV=production webpack --config webpack.config.prod.js"
```

I tried removing `NODE_ENV=production` from package.json, and it didn't seem to change anything. Is this intentional, and why?

**Comment by theneva** [comment]
Oh. Upon further investigation, setting `NODE_ENV=production` in the `package.json` script has to do with selecting `.babelrc` environment.

However, removing the plugin code setting `NODE_ENV` from `webpack.config.prod.js` does not seem to affect anything as long as `NODE_ENV=production` is set in the NPM script. That is, unless you for some reason would invoke `webpack` without going through the script.

Can I safely remove the plugin code setting `NODE_ENV` in `webpack.config.prod.js` in my own project without worrying about side effects?

**Comment by chentsulin** [comment]
`NODE_ENV=production` only set `process.env.NODE_ENV` to `production` in node environment. In frontend code which run on browsers, it should be replaced with webpack DefinePlugin, Otherwise, you will get a 

```
Uncaught ReferenceError: process is not defined(…)
```

**Comment by theneva** [comment]
Okay, I get it now. Thanks! We have no environment-specific code in the front-end app, so I'll leave it out and hope it doesn't bite me.
