### ISSUE TITLE
TypeError: this.props.data.map is not a function

### ISSUE THREAD

**Issue by lszhu** [gaearon/react-transform-boilerplate#56]
When I use the code from reactjs/react-tutorial (https://github.com/reactjs/react-tutorial/blob/master/public/scripts/example.js) and test with a modified devServer.js, as I post a new comment I got the following error:
TypeError: this.props.data.map is not a function
ProxyClass.render
webpack:///./src/App.js?:129:40
ProxyClass.proxiedMethod
webpack:///./~/react-transform-hmr/~/react-proxy/modules/createPrototypeProxy.js?:44:30
ProxyClass.tryRender
webpack:///./~/react-transform-catch-errors/lib/index.js?:36:31
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext
webpack:///./~/react/lib/ReactCompositeComponent.js?:587:34
ReactCompositeComponentMixin._renderValidatedComponent
webpack:///./~/react/lib/ReactCompositeComponent.js?:607:32
wrapper
webpack:///./~/react/lib/ReactPerf.js?:66:21
ReactCompositeComponentMixin._updateRenderedComponent
webpack:///./~/react/lib/ReactCompositeComponent.js?:560:36
ReactCompositeComponentMixin._performComponentUpdate
webpack:///./~/react/lib/ReactCompositeComponent.js?:544:10
ReactCompositeComponentMixin.updateComponent
webpack:///./~/react/lib/ReactCompositeComponent.js?:473:12
wrapper
webpack:///./~/react/lib/ReactPerf.js?:66:21

**Comment by lszhu** [comment]
I made a mistake in devServer

**Comment by aveesp** [comment]
what was the mistake??
