### ISSUE TITLE
How to update .babelrc for babel 6.x

### ISSUE THREAD

**Issue by leecade** [gaearon/react-transform-boilerplate#57]
```
{
  "stage": 0,
  "env": {
    "development": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }
      }
    }
  }
}
```

**Comment by IngenieroLata** [comment]
The stage looks like require a new attribute "presets" https://github.com/babel/babel/issues/2626 
but the actual "extra" attribute don't know the new equivalent.

**Comment by leecade** [comment]
@IngenieroLata yeah THe `extra` attr not inclued in babel 6.x documents.

**Comment by IngenieroLata** [comment]
Here are the new options, http://babeljs.io/docs/usage/options/  also the release have changed the plugin API, so it also will require an update too, http://babeljs.io/blog/2015/10/29/6.0.0/

**Comment by gaearon** [comment]
Please track https://github.com/gaearon/babel-plugin-react-transform/issues/46#issuecomment-152727158.

**Comment by alexbeletsky** [comment]
I've started to upgrage the boilerplate to Babel 6 here - [alexbeletsky/react-transform-boilerplate/commit/e0701bc](https://github.com/alexbeletsky/react-transform-boilerplate/commit/e0701bc8465c89fd07ccc3a6d3af4d364bdca2e4), but realized the dependency is actually to [gaearon/babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform).

I'd really like to make it happen and would like to help.

**Comment by gaearon** [comment]
As said above please refer to the linked issue.

**Comment by gaearon** [comment]
React Transform 2.0 was released with support for Babel 6.
