### ISSUE TITLE
.babelrc will interfere with mocha node tests.

### ISSUE THREAD

**Issue by briandipalma** [gaearon/react-transform-boilerplate#6]
The `redbox-react` package is required regardless of whether `NODE_ENV` is production or not and it references the `window` identifier which causes tests that run in node to fail. This is because babel picks up the default `.babelrc` config file and executes it, but you only really want the config file in this repo to be executed when using HMR and not during node test runs...

**Comment by briandipalma** [comment]
You can do what is suggested in this stackoverflow issue but that's a bit of a pain as you have to create a new `.babelrcfilejustfortests` file and a hook file :/ http://stackoverflow.com/questions/20049790/how-to-pass-compiler-options-to-mocha

**Comment by gaearon** [comment]
This should be reported in `redbox-react` as it's [their bug](https://github.com/KeywordBrain/redbox-react/issues/11). You are free to use any other component to report errors, such as [delicate-error-reporter](https://github.com/aulizko/delicate-error-reporter) or your own. The only requirement is for it to be a React component accepting `error` prop.

**Comment by gaearon** [comment]
You can also use `env` in `.babelrc` as [described here](https://github.com/gaearon/babel-plugin-react-transform/issues/7#issuecomment-137557443) and change tests to run with a different `NODE_ENV`.

**Comment by briandipalma** [comment]
Thanks, that worked great.
