### ISSUE TITLE
hot reloading not happening for child [dumb] components

### ISSUE THREAD

**Issue by abhijeetNmishra** [gaearon/react-transform-boilerplate#66]
I have container components and child components. Live reloading happens for my any changes in root (container) components but child components changes are not triggering even webpack rebuild.
## part of webpack.config.file
```
entry: {
    main: [
      'webpack-hot-middleware/client',
      './src/index.js'
    ]
  },
  output: {
    filename: '[name].js',
    path: path.join(__dirname, 'public'),
    publicPath: '/public/'
  },
  module: {
    loaders: [{
      test: /\.jsx?$/,
      include: path.join(__dirname, 'src'),
      loader: ['babel'],
      exclude: [nodeModulesPath],
      // Options to configure babel with
      query: {

      }
    }
```

.babelrc
```
{
  "stage": 0,
  "env": {
    "development": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }
      }
    }
  }
}
```

**Comment by morinted** [comment]
Did you resolve this? I think I'm running into the same issue and I'm curious if you have a solution. Thanks.

**Comment by bunkat** [comment]
I'm running into the same issue.  I'm using react-redux and connected components are being refreshed correctly but child components are being reloaded but not refreshed. Any solution?

**Comment by gaearon** [comment]
It's impossible to diagnose the issue without a full project reproducing them with exact repro steps.

**Comment by abhijeetNmishra** [comment]
agree to @gaearon that .. these issues are project specific and versions we are using for specific packages. For me this got resolved after upgrading to Babel 6 and cleaning up some child components. 

Please check if its happening for only few child components or all (that was the trick for me)

**Comment by bunkat** [comment]
Was hoping it was just a configuration change, working on debugging now and creating a sample project.  Thanks.

**Comment by bunkat** [comment]
I've found the problem.  If a component is wrapped in a `react-redux` connected parent component, the child component will not be reloaded on change.  Now that I figured out the root cause, it may be related to a bunch of other open issues I saw or I might have just missed something in proper usage.

For completeness, here is what I'm seeing:

***Connected component:***
````
class Form extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <form>
        {this.props.children}
      </form>
    );
  }
}

export default connect()(Form);
````

***Wrapped component:***
````
class LoginForm extends Component {
  constructor(props, context) {
    super(props, context);
  }

  render() {
    return (
      <Form id="loginForm">
        this is a test
      </Form>
    );
  }
}
````

Changing the text `this is a test` will not cause the component to re-render.  Replace `<Form>` with `<div>` and everything works as expected.  Replace `connect()(Form)` with just `Form` and everything works as expected.

It looks like the problem is in `connect.js`.
````
    if (process.env.NODE_ENV !== 'production') {
      Connect.prototype.componentWillUpdate = function componentWillUpdate() {
        if (this.version === version) {
          return;
        }

        // We are hot reloading!
        this.version = version;

        // Update the state and bindings.
        this.trySubscribe();
        this.updateStateProps();
        this.updateDispatchProps();
        this.updateState();
      };
    }
````

If you comment out the version check, the component will start updating, though it is one update behind for some reason.  For example, if you replace `this is a test` to `this is a test 2`, nothing will happen.  But if you then replace it with `this is a test 22`, it will then update to display `this is a test 2`.

**Comment by bunkat** [comment]
As I continue to hack away, looks like getting rid of the version check in `connect.js` and then force updating components twice in `react-transform-hmr` causes the componet to be updated immediately and correctly.

````
        console.info('[React Transform HMR] Patching ' + displayName);
        var instances = componentProxies[globalUniqueId].update(ReactClass);
        setTimeout(function () {
          return instances.forEach(function(instance) {
            forceUpdate(instance);
            forceUpdate(instance);
          });
        });
````

**Comment by bunkat** [comment]
Repository demonstrating issue is available at https://github.com/bunkat/counter.  It is the react-redux counter example with babel6 hot loading and a new connected wrapper component. 

To reproduce the issue:

1.  npm install
2.  npm start
3. Open browser to http://localhost:3000
4. Edit components/Counter.js
5. Modify the render method, change Clicked to Not Clicked

The module will be updated via HMR, but the Counter component will not be rendered with the new text.

**Comment by bunkat** [comment]
I've opened a new issue at https://github.com/rackt/react-redux/issues/224 since I think this is a different issue that is expected to work at the moment.

**Comment by gaearon** [comment]
Good catch, thanks for reporting and providing a full repro. This one is a bug indeed.
