### ISSUE TITLE
Make available under public domain licence

### ISSUE THREAD

**Issue by tp** [gaearon/react-transform-boilerplate#7]
Since this project is seemingly supposed to serve as the basis of other projects, I think it is confusing to the end user how to handle this already having a license.

For example, is it valid to remove the LICENSE file and then copy your licence to only the files one keeps? Then again how to handle partial files?

**Comment by gaearon** [comment]
I don't care what you do with this code, and whether the attribution is preserved.
I'll happily merge a PR that changes license to a more permissive one.

**Comment by gaearon** [comment]
Now CC0.
