### ISSUE TITLE
[HMR] The following modules couldn't be hot updated

### ISSUE THREAD

**Issue by alexander-entin** [gaearon/react-transform-boilerplate#72]
Not sure if it is an issue or support request.

clone, install, start, change color =>
[HMR] The following modules couldn't be hot updated: (Full reload needed)
[HMR]  - ./src/colors.js

Can someone confirm if it is still working with all the latest packages? 
Thank you.

**Comment by irrg** [comment]
Ah, so it's not just me. Just started using this boilerplate today, same issue.

**Comment by alexander-entin** [comment]
It worked after node update from 4.2.2 to 5.1.1

**Comment by irrg** [comment]
Still seeing the same issue after upgrading to 5.1.1 using nvm

**Comment by irrg** [comment]
nevermind, #20 helped — my .babelrc got messed up.

**Comment by luthv** [comment]
same issue here, updated to node v5.3.0 but still doesn't help, I got the exact same .babelrc as in the repo

**Comment by gaearon** [comment]
I can't reproduce this.

@luthv 

Please clone this project in a new folder, `npm install` and try again. Maybe you changed something in the configuration or in the source and forgot about it, or some dependency was buggy.

I'll happily reopen if you provide a way to reproduce.

**Comment by luthv** [comment]
I've tried it again in ubuntu and this time it worked, the one that didn't work was on windows 10 64 bit with node v4 and v5.
