### ISSUE TITLE
Stateless functional components couldn't be hot updated

### ISSUE THREAD

**Issue by mewben** [gaearon/react-transform-boilerplate#76]
In `index.js` I changed line 3 to:
```
import App  from './App';
```

then in `App.js` I changed it to become a stateless functional component like this:
```
import React from 'react';

const App = () => (
  <div>App</div>
);

export default App;
```

There's no problem in the first run. But when I changed something in `App.js`, it doesn't hot reload. The browser console throws this error:
```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
[HMR]  - ./src/App.js
```

**Comment by minooo** [comment]
I think you should     import {App}  from './App';




------------------ 原始邮件 ------------------
发件人: "mewben";<notifications@github.com>;
发送时间: 2015年12月10日(星期四) 下午4:18
收件人: "gaearon/react-transform-boilerplate"<react-transform-boilerplate@noreply.github.com>; 

主题: [react-transform-boilerplate] Stateless functional componentscouldn't be hot updated (#76)




In index.js I changed line 3 to:
 import App  from './App';  
then in App.js I changed it to become a stateless functional component like this:
 import React from 'react'; const App = () => (   <div>App</div> ); export default App;  
There's no problem in the first run. But when I changed something in App.js, it doesn't hot reload. The browser console throws this error:
 [HMR] The following modules couldn't be hot updated: (Full reload needed) [HMR]  - ./src/App.js

**Comment by mewben** [comment]
@minooo Doesn't work.
```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

**Comment by minooo** [comment]
I think it is better 

    import React, { Component } from 'react';
    export default class App extends Component {
      render() {
        return (
            <div>
              123433sdf
            </div>
        );
      }
    }

in other words,you must be sure it is a Component. Otherwise, just press F5...

**Comment by minooo** [comment]
@mewben  My English is not very good, hope you can understand the above explanation,

**Comment by hbin** [comment]
https://github.com/gaearon/babel-plugin-react-transform/issues/57

**Comment by thejameskyle** [comment]
Yeah, follow the existing issue over on gaearon/babel-plugin-react-transform#57

**Comment by gaearon** [comment]
React Hot Loader 3 supports functional components without destroying the state.
Check it out: https://github.com/gaearon/react-hot-boilerplate/pull/61
