### ISSUE TITLE
Build - NODE_ENV on Windows

### ISSUE THREAD

**Issue by n1ghtmare** [gaearon/react-transform-boilerplate#77]
Hey, I'm not sure if this is an issue per-say (or if it should be mentioned somewhere), but I found out that on Windows, this line (from `package.json`):

`NODE_ENV=production webpack --config webpack.config.prod.js`

Should be:

`SET NODE_ENV=production && webpack --config webpack.config.prod.js`

Thought I should put it out there in case someone is looking for it.

**Comment by minooo** [comment]
You are great ! I once met this problem, was going to die

**Comment by gaearon** [comment]
We should try using https://github.com/kentcdodds/cross-env.

**Comment by arve0** [comment]
Fixed in #92.
