### ISSUE TITLE
Typescript instead of babel

### ISSUE THREAD

**Issue by pepaar** [gaearon/react-transform-boilerplate#8]
Is it possible to make this work without using babel? I'm using typescript with ts-loader so I'm wondering if it's possible to make react-transform independent of babel?

**Comment by gaearon** [comment]
It should be possible to create `react-transform-loader` that extracts components from `module.exports` just like `react-hot-loader` did it. If you want to give it a try, let me know!

It will be less powerful than `babel-plugin-react-transform` though, as it won't be able to find classes that aren't exported, or classes inside functions.
