### ISSUE TITLE
HMR not working when component is inside the subdirectory

### ISSUE THREAD

**Issue by oobgam** [gaearon/react-transform-boilerplate#86]
How do you include the subdirectories of the `src` in the hot reloading?

```
src <- source
src/App.js <- triggers a webpack rebuild
src/pages/Sample.js <- does not trigger a rebuild
```

**Comment by gaearon** [comment]
Can you reproduce this on this particular project?
One caveat of Webpack HMR is you need to make sure you're using the correct casing.
For example if the file is `Sample.js` but you import it `from './pages/sample'` it won't work.

**Comment by oobgam** [comment]
@gaearon closing the issue. After checking it again, it seems to be something in my system. The changes are registered by git, but not the file system. I tried duplicating the folder itself, and it worked. Weird.

Thanks!

**Comment by mrassili** [comment]
@gaearon Your ~3 yo comment actually saved my life 😀😀
