### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier with cheap-module-eval-source-map

### ISSUE THREAD

**Issue by ustun** [gaearon/react-transform-boilerplate#87]
I see that the example uses cheap-module-eval-source-map, but when I use that, I get a weird Uncaught SyntaxError: Unexpected identifier  error.

I am using React.createClass and module.exports, not sure if it is related. 

It works if I change to source-map, but that option is too slow unfortunately
<img width="815" alt="screen shot 2015-12-24 at 1 18 30 am" src="https://cloud.githubusercontent.com/assets/94374/11986789/46c19a4a-a9dc-11e5-9590-dbf95a491c15.png">
.

**Comment by ustun** [comment]
It also works with eval and is pretty fast.

**Comment by gaearon** [comment]
Please provide the minimal project reproducing this exact problem.
It's impossible to help without a way to reproduce.

**Comment by gaearon** [comment]
I'm closing. Will be happy to reopen if you provide a way to reproduce.

**Comment by ustun** [comment]
Thanks, I'll reopen if I can reproduce minimally, but eval works fine. 

Thanks again for the great project. 

Üstün

24 Ara 2015 tarihinde 21:09 saatinde, Dan Abramov <notifications@github.com> şunları yazdı:

**Comment by gaearon** [comment]
:+1:
