### ISSUE TITLE
Support for Electron app?

### ISSUE THREAD

**Issue by nlhkh** [gaearon/react-transform-boilerplate#88]
Although not in the web context, I think Electron app can benefit greatly from this boilerplate. Electron cannot hot reload the react component however, because when the is `target: "atom"`, webpack will not bundle HMR. Remove the target let React to hot reload, but that would mean that the NodeJS modules cannot be used (as webpack will try to bundle them).

**Comment by gaearon** [comment]
Sure, it would be cool.
We won't support it (it's a big undertaking) but we'd be happy to link to it if you or someone else sets it up.

**Comment by chentsulin** [comment]
@nlhkh There is a [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) solve the problem you mentioned.
