### ISSUE TITLE
Webpack dev server support

### ISSUE THREAD

**Issue by alexbeletsky** [gaearon/react-transform-boilerplate#94]
Thanks a lot for this boilerplate project. 

You use express + middleware here.. But is that possible to use webpack dev server for the same behaviour?

I tried that and was able to run it. There is one particular feature that works in this boilerplate, doesn't work in my project. When I do some incorrect JSX tag, say `<h1>Hello</h2>` in boilerplate, an error is nicely rendered in error `div`. With webpack dev server, I can see that page is fully reloaded and error only visible in dev tools console (page itself remains blank).

If I can provide further details, please let me know.

**Comment by craigjennings11** [comment]
This took me a little while to find, too, but you're talking about a feature that only webpack-hot-middleware provides:
> Additionally, webpack-hot-middleware displays syntax errors in an overlay, which WebpackDevServer doesn’t do.
under https://github.com/gaearon/react-transform-boilerplate#can-i-use-webpackdevserver-with-this.

**Comment by alexbeletsky** [comment]
Got it, thanks a lot @craigjennings11
