### ISSUE TITLE
Certain Imports Breaks Reloading?

### ISSUE THREAD

**Issue by jupl** [gaearon/react-transform-boilerplate#95]
I was messing around with an app using this boilerplate and at times reload no longer works. The simplest example to reproduce is that if I clone this repo and run the app with a modified `index.js`:

```js
import React from 'react';
import { render } from 'react-dom';
import { App } from './App';
import { NICE } from './colors';

render(<App />, document.getElementById('root'));
console.log(NICE);
```

Without this change when I change colors hot reload works, but with this change the following appears in terminal:

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
[HMR]  - ./src/colors.js
```

**Comment by gaearon** [comment]
Please see https://github.com/gaearon/react-transform-boilerplate/issues/120#issuecomment-192716194 for an explanation for why this happens. If import chain doesn’t end in a component, hot update will fail unless you explicitly use `module.hot.accept` API.
