### ISSUE TITLE
React-Relay [HMR] Full reload needed

### ISSUE THREAD

**Issue by MarioJerkovicDickeys** [gaearon/react-transform-boilerplate#98]
In this example I have implemented React-Relay:
.babelrc
```
  "presets": ["react", "stage-0", "es2015"],
  "plugins": ["transform-class-properties","./build/babelRelayPlugin"],
  "env": {
    "development": {
    "plugins": ["transform-class-properties","./build/babelRelayPlugin"],
      "presets": ["react-hmre"]
    }
  }
}

```
index.js

```
import 'babel-polyfill';

import App from './App';
import AppHomeRoute from './queries/MainQueries';
import React from 'react';
import ReactDOM from 'react-dom';
import Relay from 'react-relay';
import RelayStoreData from 'react-relay/lib/RelayStoreData';

const GRAPHQL_URL = 'https://test-mariojerkovic.c9users.io/?_c9_id=livepreview1&_c9_host=https://ide.c9.io';

Relay.injectNetworkLayer(new Relay.DefaultNetworkLayer(GRAPHQL_URL));

RelayStoreData.getDefaultInstance().getChangeEmitter().injectBatchingStrategy(() => {});

ReactDOM.render(
    <Relay.RootContainer
        Component={App}
        route={new AppHomeRoute()}
    />,
    document.getElementById('root')
);
```

In App.js I only edited the last part to add Relay.createContainer
```
    export default Relay.createContainer(App, {
    fragments: {
        factions: () => Relay.QL`
          fragment on Faction @relay(plural: true) {
            id,
            name
          }
        `,
},
});
```

On each edit in every single .js file webpack returns [HMR] The following modules couldn't be hot updated: (Full reload needed). Only if I refresh the app with F5 changes are vissible

**Comment by schickling** [comment]
Facing the same problem. @MarioJerkovicDickeys did you figure it out eventually?

**Comment by gaearon** [comment]
Please post a project reproducing the issue when asking for help :smile: .
I’d *love* to look into this but every extra 5 minutes make a difference between doing and not doing it.

If I have to set up dependencies myself and copy-paste snippets until I can reproduce the issue, I won’t be looking into it. If you provide a project that is easy to run with `npm install` and `npm start`, with exact instructions to reproduce the issue, I can look into it.

**Comment by schickling** [comment]
Turns out by preparing an example project for you and reducing the project to a minimum I eventually found the problem (was related to `webpack-dev-server`). Sorry for the inconveniences!

**Comment by gaearon** [comment]
:+1: 

That’s how it’s usually solved :wink:

**Comment by Ebram-Tharwat** [comment]
@schickling , can you please post your solution, as I'm facing the same issue currently.
