### ISSUE TITLE
Error with source-map

### ISSUE THREAD

**Issue by Teemobustin** [gaearon/react-transform-boilerplate#99]
![screen shot 2016-01-15 at 5 26 06 pm](https://cloud.githubusercontent.com/assets/14071345/12370228/ebb2782a-bc43-11e5-81ef-a0ea218d24c6.png)

After I install everything and try to start the program, an error pops out,

Something wrong with source-map, I have try to install source-map again, but the error shows up again.

![screen shot 2016-01-15 at 5 30 06 pm](https://cloud.githubusercontent.com/assets/14071345/12370235/326cff1a-bc44-11e5-8b43-699aff3747ee.png)

Can not start this program

**Comment by gaearon** [comment]
I can’t reproduce this. Try deleting `node_modules` and running `npm install` again. It was likely some temporary network issue that prevented a certain file from being installed, or a dependency problem that has since been fixed.
